### ISSUE TITLE
Error when attempting to use countries with a comma

### ISSUE THREAD

**Issue by joshcannotcode** [MM-coder/coronavirus-wallpaper#11]
e.g. United Kingdom, GB

When doing so this error is visible in the console: http://prntscr.com/rkkxu0

**Comment by MM-coder** [comment]
Do you have the latest version?

**Comment by joshcannotcode** [comment]
> Do you have the latest version?

Yeah.

**Comment by MM-coder** [comment]
Just released a new version, it works for me on local

**Comment by MM-coder** [comment]
Can you confirm it works?

**Comment by joshcannotcode** [comment]
> Can you confirm it works?

Will do so tmr morning :)

**Comment by joshcannotcode** [comment]
All fixed, thanks for fixing.
